#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace X.App
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="x.link")]
	public partial class DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertx_dict(x_dict instance);
    partial void Updatex_dict(x_dict instance);
    partial void Deletex_dict(x_dict instance);
    partial void Insertx_url(x_url instance);
    partial void Updatex_url(x_url instance);
    partial void Deletex_url(x_url instance);
    partial void Insertx_user(x_user instance);
    partial void Updatex_user(x_user instance);
    partial void Deletex_user(x_user instance);
    partial void Insertx_art(x_art instance);
    partial void Updatex_art(x_art instance);
    partial void Deletex_art(x_art instance);
    #endregion
		
		public DBDataContext() : 
				base(global::X.App.Properties.Settings.Default.x_linkConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<x_dict> x_dict
		{
			get
			{
				return this.GetTable<x_dict>();
			}
		}
		
		public System.Data.Linq.Table<x_url> x_url
		{
			get
			{
				return this.GetTable<x_url>();
			}
		}
		
		public System.Data.Linq.Table<x_user> x_user
		{
			get
			{
				return this.GetTable<x_user>();
			}
		}
		
		public System.Data.Linq.Table<x_art> x_art
		{
			get
			{
				return this.GetTable<x_art>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.x_dict")]
	public partial class x_dict : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _dict_id;
		
		private string _code;
		
		private string _img;
		
		private string _name;
		
		private string _jp;
		
		private string _upval;
		
		private string _value;
		
		private System.Nullable<int> _sort;
		
		private string _f1;
		
		private string _f2;
		
		private System.Nullable<int> _f3;
		
		private System.Nullable<int> _f4;
		
		private System.Nullable<int> _f5;
		
		private System.Nullable<int> _f6;
		
		private System.Nullable<int> _f7;
		
		private System.Nullable<int> _f8;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondict_idChanging(long value);
    partial void Ondict_idChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void OnimgChanging(string value);
    partial void OnimgChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnjpChanging(string value);
    partial void OnjpChanged();
    partial void OnupvalChanging(string value);
    partial void OnupvalChanged();
    partial void OnvalueChanging(string value);
    partial void OnvalueChanged();
    partial void OnsortChanging(System.Nullable<int> value);
    partial void OnsortChanged();
    partial void Onf1Changing(string value);
    partial void Onf1Changed();
    partial void Onf2Changing(string value);
    partial void Onf2Changed();
    partial void Onf3Changing(System.Nullable<int> value);
    partial void Onf3Changed();
    partial void Onf4Changing(System.Nullable<int> value);
    partial void Onf4Changed();
    partial void Onf5Changing(System.Nullable<int> value);
    partial void Onf5Changed();
    partial void Onf6Changing(System.Nullable<int> value);
    partial void Onf6Changed();
    partial void Onf7Changing(System.Nullable<int> value);
    partial void Onf7Changed();
    partial void Onf8Changing(System.Nullable<int> value);
    partial void Onf8Changed();
    #endregion
		
		public x_dict()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dict_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long dict_id
		{
			get
			{
				return this._dict_id;
			}
			set
			{
				if ((this._dict_id != value))
				{
					this.Ondict_idChanging(value);
					this.SendPropertyChanging();
					this._dict_id = value;
					this.SendPropertyChanged("dict_id");
					this.Ondict_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="NVarChar(20)")]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="NVarChar(200)")]
		public string img
		{
			get
			{
				return this._img;
			}
			set
			{
				if ((this._img != value))
				{
					this.OnimgChanging(value);
					this.SendPropertyChanging();
					this._img = value;
					this.SendPropertyChanged("img");
					this.OnimgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jp", DbType="NVarChar(50)")]
		public string jp
		{
			get
			{
				return this._jp;
			}
			set
			{
				if ((this._jp != value))
				{
					this.OnjpChanging(value);
					this.SendPropertyChanging();
					this._jp = value;
					this.SendPropertyChanged("jp");
					this.OnjpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_upval", DbType="NVarChar(10)")]
		public string upval
		{
			get
			{
				return this._upval;
			}
			set
			{
				if ((this._upval != value))
				{
					this.OnupvalChanging(value);
					this.SendPropertyChanging();
					this._upval = value;
					this.SendPropertyChanged("upval");
					this.OnupvalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value", DbType="NVarChar(100)")]
		public string value
		{
			get
			{
				return this._value;
			}
			set
			{
				if ((this._value != value))
				{
					this.OnvalueChanging(value);
					this.SendPropertyChanging();
					this._value = value;
					this.SendPropertyChanged("value");
					this.OnvalueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sort", DbType="Int")]
		public System.Nullable<int> sort
		{
			get
			{
				return this._sort;
			}
			set
			{
				if ((this._sort != value))
				{
					this.OnsortChanging(value);
					this.SendPropertyChanging();
					this._sort = value;
					this.SendPropertyChanged("sort");
					this.OnsortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f1", DbType="NVarChar(200)")]
		public string f1
		{
			get
			{
				return this._f1;
			}
			set
			{
				if ((this._f1 != value))
				{
					this.Onf1Changing(value);
					this.SendPropertyChanging();
					this._f1 = value;
					this.SendPropertyChanged("f1");
					this.Onf1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f2", DbType="NVarChar(200)")]
		public string f2
		{
			get
			{
				return this._f2;
			}
			set
			{
				if ((this._f2 != value))
				{
					this.Onf2Changing(value);
					this.SendPropertyChanging();
					this._f2 = value;
					this.SendPropertyChanged("f2");
					this.Onf2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f3", DbType="Int")]
		public System.Nullable<int> f3
		{
			get
			{
				return this._f3;
			}
			set
			{
				if ((this._f3 != value))
				{
					this.Onf3Changing(value);
					this.SendPropertyChanging();
					this._f3 = value;
					this.SendPropertyChanged("f3");
					this.Onf3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f4", DbType="Int")]
		public System.Nullable<int> f4
		{
			get
			{
				return this._f4;
			}
			set
			{
				if ((this._f4 != value))
				{
					this.Onf4Changing(value);
					this.SendPropertyChanging();
					this._f4 = value;
					this.SendPropertyChanged("f4");
					this.Onf4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f5", DbType="Int")]
		public System.Nullable<int> f5
		{
			get
			{
				return this._f5;
			}
			set
			{
				if ((this._f5 != value))
				{
					this.Onf5Changing(value);
					this.SendPropertyChanging();
					this._f5 = value;
					this.SendPropertyChanged("f5");
					this.Onf5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f6", DbType="Int")]
		public System.Nullable<int> f6
		{
			get
			{
				return this._f6;
			}
			set
			{
				if ((this._f6 != value))
				{
					this.Onf6Changing(value);
					this.SendPropertyChanging();
					this._f6 = value;
					this.SendPropertyChanged("f6");
					this.Onf6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f7", DbType="Int")]
		public System.Nullable<int> f7
		{
			get
			{
				return this._f7;
			}
			set
			{
				if ((this._f7 != value))
				{
					this.Onf7Changing(value);
					this.SendPropertyChanging();
					this._f7 = value;
					this.SendPropertyChanged("f7");
					this.Onf7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f8", DbType="Int")]
		public System.Nullable<int> f8
		{
			get
			{
				return this._f8;
			}
			set
			{
				if ((this._f8 != value))
				{
					this.Onf8Changing(value);
					this.SendPropertyChanging();
					this._f8 = value;
					this.SendPropertyChanged("f8");
					this.Onf8Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.x_url")]
	public partial class x_url : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _url_id;
		
		private long _user_id;
		
		private System.Nullable<int> _cate;
		
		private string _url;
		
		private string _title;
		
		private string _alt;
		
		private string _icon;
		
		private System.Nullable<int> _top;
		
		private string _tags;
		
		private string _remark;
		
		private System.Nullable<System.DateTime> _ctime;
		
		private EntityRef<x_user> _x_user;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onurl_idChanging(long value);
    partial void Onurl_idChanged();
    partial void Onuser_idChanging(long value);
    partial void Onuser_idChanged();
    partial void OncateChanging(System.Nullable<int> value);
    partial void OncateChanged();
    partial void OnurlChanging(string value);
    partial void OnurlChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnaltChanging(string value);
    partial void OnaltChanged();
    partial void OniconChanging(string value);
    partial void OniconChanged();
    partial void OntopChanging(System.Nullable<int> value);
    partial void OntopChanged();
    partial void OntagsChanging(string value);
    partial void OntagsChanged();
    partial void OnremarkChanging(string value);
    partial void OnremarkChanged();
    partial void OnctimeChanging(System.Nullable<System.DateTime> value);
    partial void OnctimeChanged();
    #endregion
		
		public x_url()
		{
			this._x_user = default(EntityRef<x_user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_url_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long url_id
		{
			get
			{
				return this._url_id;
			}
			set
			{
				if ((this._url_id != value))
				{
					this.Onurl_idChanging(value);
					this.SendPropertyChanging();
					this._url_id = value;
					this.SendPropertyChanged("url_id");
					this.Onurl_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="BigInt NOT NULL")]
		public long user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					if (this._x_user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cate", DbType="Int")]
		public System.Nullable<int> cate
		{
			get
			{
				return this._cate;
			}
			set
			{
				if ((this._cate != value))
				{
					this.OncateChanging(value);
					this.SendPropertyChanging();
					this._cate = value;
					this.SendPropertyChanged("cate");
					this.OncateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_url", DbType="NVarChar(250)")]
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				if ((this._url != value))
				{
					this.OnurlChanging(value);
					this.SendPropertyChanging();
					this._url = value;
					this.SendPropertyChanged("url");
					this.OnurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(150)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alt", DbType="NVarChar(150)")]
		public string alt
		{
			get
			{
				return this._alt;
			}
			set
			{
				if ((this._alt != value))
				{
					this.OnaltChanging(value);
					this.SendPropertyChanging();
					this._alt = value;
					this.SendPropertyChanged("alt");
					this.OnaltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_icon", DbType="NVarChar(250)")]
		public string icon
		{
			get
			{
				return this._icon;
			}
			set
			{
				if ((this._icon != value))
				{
					this.OniconChanging(value);
					this.SendPropertyChanging();
					this._icon = value;
					this.SendPropertyChanged("icon");
					this.OniconChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[top]", Storage="_top", DbType="Int")]
		public System.Nullable<int> top
		{
			get
			{
				return this._top;
			}
			set
			{
				if ((this._top != value))
				{
					this.OntopChanging(value);
					this.SendPropertyChanging();
					this._top = value;
					this.SendPropertyChanged("top");
					this.OntopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tags", DbType="NVarChar(550)")]
		public string tags
		{
			get
			{
				return this._tags;
			}
			set
			{
				if ((this._tags != value))
				{
					this.OntagsChanging(value);
					this.SendPropertyChanging();
					this._tags = value;
					this.SendPropertyChanged("tags");
					this.OntagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark", DbType="NVarChar(450)")]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this.OnremarkChanging(value);
					this.SendPropertyChanging();
					this._remark = value;
					this.SendPropertyChanged("remark");
					this.OnremarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ctime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ctime
		{
			get
			{
				return this._ctime;
			}
			set
			{
				if ((this._ctime != value))
				{
					this.OnctimeChanging(value);
					this.SendPropertyChanging();
					this._ctime = value;
					this.SendPropertyChanged("ctime");
					this.OnctimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="x_user_x_url", Storage="_x_user", ThisKey="user_id", OtherKey="user_id", IsForeignKey=true)]
		public x_user x_user
		{
			get
			{
				return this._x_user.Entity;
			}
			set
			{
				x_user previousValue = this._x_user.Entity;
				if (((previousValue != value) 
							|| (this._x_user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._x_user.Entity = null;
						previousValue.x_url.Remove(this);
					}
					this._x_user.Entity = value;
					if ((value != null))
					{
						value.x_url.Add(this);
						this._user_id = value.user_id;
					}
					else
					{
						this._user_id = default(long);
					}
					this.SendPropertyChanged("x_user");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.x_user")]
	public partial class x_user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _user_id;
		
		private string _uid;
		
		private string _pwd;
		
		private string _name;
		
		private string _role;
		
		private string _tel;
		
		private System.Nullable<System.DateTime> _ctime;
		
		private string _ukey;
		
		private EntitySet<x_url> _x_url;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(long value);
    partial void Onuser_idChanged();
    partial void OnuidChanging(string value);
    partial void OnuidChanged();
    partial void OnpwdChanging(string value);
    partial void OnpwdChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnroleChanging(string value);
    partial void OnroleChanged();
    partial void OntelChanging(string value);
    partial void OntelChanged();
    partial void OnctimeChanging(System.Nullable<System.DateTime> value);
    partial void OnctimeChanged();
    partial void OnukeyChanging(string value);
    partial void OnukeyChanged();
    #endregion
		
		public x_user()
		{
			this._x_url = new EntitySet<x_url>(new Action<x_url>(this.attach_x_url), new Action<x_url>(this.detach_x_url));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", DbType="NVarChar(64)")]
		public string uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pwd", DbType="NVarChar(64)")]
		public string pwd
		{
			get
			{
				return this._pwd;
			}
			set
			{
				if ((this._pwd != value))
				{
					this.OnpwdChanging(value);
					this.SendPropertyChanging();
					this._pwd = value;
					this.SendPropertyChanged("pwd");
					this.OnpwdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(20)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="NVarChar(50)")]
		public string role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this.OnroleChanging(value);
					this.SendPropertyChanging();
					this._role = value;
					this.SendPropertyChanged("role");
					this.OnroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel", DbType="NVarChar(11)")]
		public string tel
		{
			get
			{
				return this._tel;
			}
			set
			{
				if ((this._tel != value))
				{
					this.OntelChanging(value);
					this.SendPropertyChanging();
					this._tel = value;
					this.SendPropertyChanged("tel");
					this.OntelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ctime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ctime
		{
			get
			{
				return this._ctime;
			}
			set
			{
				if ((this._ctime != value))
				{
					this.OnctimeChanging(value);
					this.SendPropertyChanging();
					this._ctime = value;
					this.SendPropertyChanged("ctime");
					this.OnctimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ukey", DbType="NVarChar(80)")]
		public string ukey
		{
			get
			{
				return this._ukey;
			}
			set
			{
				if ((this._ukey != value))
				{
					this.OnukeyChanging(value);
					this.SendPropertyChanging();
					this._ukey = value;
					this.SendPropertyChanged("ukey");
					this.OnukeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="x_user_x_url", Storage="_x_url", ThisKey="user_id", OtherKey="user_id")]
		public EntitySet<x_url> x_url
		{
			get
			{
				return this._x_url;
			}
			set
			{
				this._x_url.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_x_url(x_url entity)
		{
			this.SendPropertyChanging();
			entity.x_user = this;
		}
		
		private void detach_x_url(x_url entity)
		{
			this.SendPropertyChanging();
			entity.x_user = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[x.art]")]
	public partial class x_art : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _call_index;
		
		private string _title;
		
		private string _link_url;
		
		private string _img_url;
		
		private string _tags;
		
		private string _zhaiyao;
		
		private string _content;
		
		private System.Nullable<int> _sort_id;
		
		private System.Nullable<int> _click;
		
		private System.Nullable<byte> _status;
		
		private System.Nullable<byte> _is_msg;
		
		private System.Nullable<byte> _is_top;
		
		private System.Nullable<byte> _is_red;
		
		private System.Nullable<byte> _is_hot;
		
		private System.Nullable<byte> _is_slide;
		
		private System.Nullable<System.DateTime> _add_time;
		
		private System.Nullable<System.DateTime> _update_time;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Oncall_indexChanging(string value);
    partial void Oncall_indexChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void Onlink_urlChanging(string value);
    partial void Onlink_urlChanged();
    partial void Onimg_urlChanging(string value);
    partial void Onimg_urlChanged();
    partial void OntagsChanging(string value);
    partial void OntagsChanged();
    partial void OnzhaiyaoChanging(string value);
    partial void OnzhaiyaoChanged();
    partial void OncontentChanging(string value);
    partial void OncontentChanged();
    partial void Onsort_idChanging(System.Nullable<int> value);
    partial void Onsort_idChanged();
    partial void OnclickChanging(System.Nullable<int> value);
    partial void OnclickChanged();
    partial void OnstatusChanging(System.Nullable<byte> value);
    partial void OnstatusChanged();
    partial void Onis_msgChanging(System.Nullable<byte> value);
    partial void Onis_msgChanged();
    partial void Onis_topChanging(System.Nullable<byte> value);
    partial void Onis_topChanged();
    partial void Onis_redChanging(System.Nullable<byte> value);
    partial void Onis_redChanged();
    partial void Onis_hotChanging(System.Nullable<byte> value);
    partial void Onis_hotChanged();
    partial void Onis_slideChanging(System.Nullable<byte> value);
    partial void Onis_slideChanged();
    partial void Onadd_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onadd_timeChanged();
    partial void Onupdate_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onupdate_timeChanged();
    #endregion
		
		public x_art()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_call_index", DbType="NVarChar(50)")]
		public string call_index
		{
			get
			{
				return this._call_index;
			}
			set
			{
				if ((this._call_index != value))
				{
					this.Oncall_indexChanging(value);
					this.SendPropertyChanging();
					this._call_index = value;
					this.SendPropertyChanged("call_index");
					this.Oncall_indexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(100)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link_url", DbType="NVarChar(255)")]
		public string link_url
		{
			get
			{
				return this._link_url;
			}
			set
			{
				if ((this._link_url != value))
				{
					this.Onlink_urlChanging(value);
					this.SendPropertyChanging();
					this._link_url = value;
					this.SendPropertyChanged("link_url");
					this.Onlink_urlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img_url", DbType="NVarChar(255)")]
		public string img_url
		{
			get
			{
				return this._img_url;
			}
			set
			{
				if ((this._img_url != value))
				{
					this.Onimg_urlChanging(value);
					this.SendPropertyChanging();
					this._img_url = value;
					this.SendPropertyChanged("img_url");
					this.Onimg_urlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tags", DbType="NVarChar(500)")]
		public string tags
		{
			get
			{
				return this._tags;
			}
			set
			{
				if ((this._tags != value))
				{
					this.OntagsChanging(value);
					this.SendPropertyChanging();
					this._tags = value;
					this.SendPropertyChanged("tags");
					this.OntagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zhaiyao", DbType="NVarChar(255)")]
		public string zhaiyao
		{
			get
			{
				return this._zhaiyao;
			}
			set
			{
				if ((this._zhaiyao != value))
				{
					this.OnzhaiyaoChanging(value);
					this.SendPropertyChanging();
					this._zhaiyao = value;
					this.SendPropertyChanged("zhaiyao");
					this.OnzhaiyaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string content
		{
			get
			{
				return this._content;
			}
			set
			{
				if ((this._content != value))
				{
					this.OncontentChanging(value);
					this.SendPropertyChanging();
					this._content = value;
					this.SendPropertyChanged("content");
					this.OncontentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sort_id", DbType="Int")]
		public System.Nullable<int> sort_id
		{
			get
			{
				return this._sort_id;
			}
			set
			{
				if ((this._sort_id != value))
				{
					this.Onsort_idChanging(value);
					this.SendPropertyChanging();
					this._sort_id = value;
					this.SendPropertyChanged("sort_id");
					this.Onsort_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_click", DbType="Int")]
		public System.Nullable<int> click
		{
			get
			{
				return this._click;
			}
			set
			{
				if ((this._click != value))
				{
					this.OnclickChanging(value);
					this.SendPropertyChanging();
					this._click = value;
					this.SendPropertyChanged("click");
					this.OnclickChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="TinyInt")]
		public System.Nullable<byte> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_msg", DbType="TinyInt")]
		public System.Nullable<byte> is_msg
		{
			get
			{
				return this._is_msg;
			}
			set
			{
				if ((this._is_msg != value))
				{
					this.Onis_msgChanging(value);
					this.SendPropertyChanging();
					this._is_msg = value;
					this.SendPropertyChanged("is_msg");
					this.Onis_msgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_top", DbType="TinyInt")]
		public System.Nullable<byte> is_top
		{
			get
			{
				return this._is_top;
			}
			set
			{
				if ((this._is_top != value))
				{
					this.Onis_topChanging(value);
					this.SendPropertyChanging();
					this._is_top = value;
					this.SendPropertyChanged("is_top");
					this.Onis_topChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_red", DbType="TinyInt")]
		public System.Nullable<byte> is_red
		{
			get
			{
				return this._is_red;
			}
			set
			{
				if ((this._is_red != value))
				{
					this.Onis_redChanging(value);
					this.SendPropertyChanging();
					this._is_red = value;
					this.SendPropertyChanged("is_red");
					this.Onis_redChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_hot", DbType="TinyInt")]
		public System.Nullable<byte> is_hot
		{
			get
			{
				return this._is_hot;
			}
			set
			{
				if ((this._is_hot != value))
				{
					this.Onis_hotChanging(value);
					this.SendPropertyChanging();
					this._is_hot = value;
					this.SendPropertyChanged("is_hot");
					this.Onis_hotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_slide", DbType="TinyInt")]
		public System.Nullable<byte> is_slide
		{
			get
			{
				return this._is_slide;
			}
			set
			{
				if ((this._is_slide != value))
				{
					this.Onis_slideChanging(value);
					this.SendPropertyChanging();
					this._is_slide = value;
					this.SendPropertyChanged("is_slide");
					this.Onis_slideChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_add_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> add_time
		{
			get
			{
				return this._add_time;
			}
			set
			{
				if ((this._add_time != value))
				{
					this.Onadd_timeChanging(value);
					this.SendPropertyChanging();
					this._add_time = value;
					this.SendPropertyChanged("add_time");
					this.Onadd_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_time
		{
			get
			{
				return this._update_time;
			}
			set
			{
				if ((this._update_time != value))
				{
					this.Onupdate_timeChanging(value);
					this.SendPropertyChanging();
					this._update_time = value;
					this.SendPropertyChanged("update_time");
					this.Onupdate_timeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
